# Generated by Django 4.2 on 2024-05-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
